receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: otel-logs

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
